name: Run Unittests

on:
  push:
    branches: [ master, release ]
  pull_request:
    branches: [ master, release ]
  
jobs:
  test:
    name: Run Unittests
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      # The action checks out the branch, which triggered the event by default.
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with: 
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[qopt_tests]
        python -m pip install pytest-cov
        
    - name: Run the tests
      run: |
        python -m pytest qopt_tests --cov=qopt --cov-report=xml
        # it is important to use python -m because it adds the current directory to the path!
        
    - name: Upload code coverage
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        name: ${{ matrix.python-version }}
        env_vars: OS,PYTHON
        fail_ci_if_error: true
